name: 'Setup Docker build env'
description: 'Set up docker builder and cache args'

runs:
  using: 'composite'
  steps:
    - name: Generate docker build cache arg
      shell: bash
      run: |
        echo "DOCKER_BUILD_CACHE_ARG=--cache-from type=gha --cache-to type=gha,mode=max --load" >> "$GITHUB_ENV"
