name: Periodic Silent Merge Check

on:
  schedule:
    - cron: "0 0 * * 0"  # Sunday 00:00 UTC
  workflow_dispatch:

jobs:
  verify-prs:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: read
      contents: read

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential

      - name: List open PRs
        id: prs
        run: |
          prs=$(gh pr list --state open --json number --jq '.[].number')
          echo "prs=$prs" >> $GITHUB_ENV

      - name: Process PRs
        run: |
          for pr in $prs; do
            echo "Checking PR #$pr"

            # Fetch PR metadata
            pr_json=$(gh api repos/${GITHUB_REPOSITORY}/pulls/$pr)
            draft=$(echo "$pr_json" | jq -r '.draft')
            mergeable_state=$(echo "$pr_json" | jq -r '.mergeable_state')
            head_sha=$(echo "$pr_json" | jq -r '.head.sha')

            if [ "$draft" = "true" ]; then
              echo "PR #$pr is draft, skipping."
              continue
            fi

            if [ "$mergeable_state" = "dirty" ]; then
              echo "PR #$pr has merge conflicts, reporting failed check."
              gh api repos/${GITHUB_REPOSITORY}/check-runs \
                -X POST \
                -F "name=Conflict Check" \
                -F "head_sha=$head_sha" \
                -F "status=completed" \
                -F "conclusion=failure" \
                -F "output[title]=Merge conflicts detected" \
                -F "output[summary]=This PR cannot be merged due to conflicts."
              continue
            fi

            # --- Check existing check runs ---
            failed_checks=$(gh api repos/${GITHUB_REPOSITORY}/commits/$head_sha/check-runs \
              --jq '.check_runs[] | select(.conclusion=="failure") | .name' || true)

            if [ -n "$failed_checks" ]; then
              echo "PR #$pr already has failing check runs: $failed_checks. Skipping."
              continue
            fi

            # --- Run build/tests ---
            git fetch origin pull/$pr/head:pr-$pr
            git checkout pr-$pr

            mkdir -p build && cd build
            cmake ..
            if make -j$(nproc) && ctest --output-on-failure; then
              conclusion=success
              summary="CMake build and tests passed."
            else
              conclusion=failure
              summary="CMake build or tests failed."
            fi

            # --- Report result as a new check run ---
            gh api repos/${GITHUB_REPOSITORY}/check-runs \
              -X POST \
              -F "name=CMake Build & Test" \
              -F "head_sha=$head_sha" \
              -F "status=completed" \
              -F "conclusion=$conclusion" \
              -F "output[title]=CMake Build & Test" \
              -F "output[summary]=$summary"

          done
